name: root
channels:
  - conda-forge
dependencies:
  - flake8
  - scipy
  - numpy
  - pandas
  - jupyter
  - matplotlib
  - scikit-learn>=0.19
  - pip:
      - https://api.github.com/repos/paris-saclay-cds/ramp-workflow/zipball/master
